version: "3"

services:

  server:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 8090
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
